logoText = "è¯¸è‘›é’" # æ˜¾ç¤ºåœ¨ç½‘ç«™å¯¼èˆªæ ä¸­çš„å¾½æ ‡æ–‡æœ¬ã€‚
logoType = "squre" # long, short ,squreå½¢çŠ¶åŒ…å«å¾½æ ‡æ–‡æœ¬ï¼Œlongï¼šçŸ©å½¢å½¢çŠ¶ä¸åŒ…å«å¾½æ ‡æ–‡æœ¬
description = "è¯·è·Ÿæˆ‘ä¸€èµ·è¸ä¸Šç¼–ç¨‹ä¹‹æ—…å§ï¼"
custom_css = []
custom_js = []
# favicon = "/images/favicon/favicon.ico"
useFaviconGenerator = false # https://www.favicon-generator.org/
meta_image = "/favicon/maidan3.ico"
themecolor = ""

themeOptions = ["dark", "light", "hacker", "solarized", "kimbie"] # é€‰æ‹©ä¸åŒçš„ä¸»é¢˜
# ä¸å…è®¸å‡ºç°åœ¨ä¸»é¡µçš„ç›®å½•å
notAllowedTypesInHome = ["exercise","touge","interview","databases","contact", "about","archive", "presentation", "resume","intelligence","devil_footprints","write","novel"]
# ä¸å…è®¸å‡ºç°åœ¨ä¸»é¡µä¾§è¾¹æ çš„ç›®å½•å
notAllowedTypesInHomeSidebar = ["exercise","compare","touge","about","gallery","archive","recommend_sites","intelligence","devil_footprints","write","novel"]
# ä¸å…è®¸è¢«æ—¥å¿—è®°å½•çš„ç›®å½•åï¼ˆä»¥ååˆ é™¤æ—¥å¿—ï¼‰
notAllowedTypesInArchive = ["touge","gallery","archive","write","exercise","about"]

notAllowedTypesInHomeFeed = ["about", "archive", "contact", "talks", "showcase", "publication", "presentation", "resume", "gallery"]
# ä¸»é¡µå¤§å°
viewportSize = "normal" # widest, wider, wide, normal, narrow
# ç¿»é¡µæ•ˆæœ
enableUiAnimation = true
# å¦‚æœä¸ºtrueï¼Œåˆ™åœ¨æµè§ˆå™¨ä¸­ç¦ç”¨javascriptæ—¶ï¼Œåšå®¢å†…å®¹å°†è¢«éšè—ã€‚
hideSingleContentsWhenJSDisabled = false
# å¦‚æœä¸ºtrueï¼Œåˆ™å¯ä»¥åœ¨å¸–å­ä¸­è®¾ç½®å›ºå®šçš„å‰ç½®å†…å®¹ã€‚å›ºå®šçš„å¸–å­æ˜¾ç¤ºåœ¨æ‚¨çš„å¸–å­åˆ—è¡¨çš„é¡¶éƒ¨ã€‚
enablePinnedPosts = true
minItemsToShowInTagCloud = 1 # æ ‡ç­¾äº‘ä¸­æ˜¾ç¤ºçš„æœ€å°‘é¡¹ç›®

# appbar
# æ˜¯å¦å¼€å¯ä¸»é¡µæœç´¢
enableAppbarSearchIcon = true
# è¯­è¨€åˆ‡æ¢å›¾æ ‡æ˜¯å¦æ˜¾ç¤º
enableAppbarLangIcon = false

# header
homeHeaderType = "text" # text, img, slide, typewriteré€‰æ‹©content(_index.md)æ ¼å¼
# åœ¨ç§»åŠ¨è®¾å¤‡ä¸Šæ˜¯å¦éšè—é¦–é¡µæ ‡é¢˜ã€‚
hideHomeHeaderWhenMobile = false

# menu
# å¦‚æœä¸ºtrueï¼Œåˆ™å¯ä»¥åœ¨ç§»åŠ¨è®¾å¤‡ä¸Šä½¿ç”¨åˆ†ç±»æ³•èœå•ã€‚
showMobileMenuTerms = ["tags", "categories", "series"]

# body
# æ˜¾ç¤ºè·¯å¾„
enableBreadcrumb = true
enablePhotoSwipe = true
enableSearch = true # ä½¿ç”¨Fuseè¿›è¡Œç«™ç‚¹æœç´¢
enableSearchHighlight = true # ä¸ºtrueæ—¶ï¼Œæœç´¢å…³é”®å­—å°†çªå‡ºæ˜¾ç¤º
enableGoToTop = true # æ»šåŠ¨åˆ°é¡¶éƒ¨
enableWhoami = true # åœ¨å•é¡µæœ«å°¾
summaryShape = "classic" # card, classic, compactæ‘˜è¦å½¢çŠ¶
searchResultPosition = "main" # side, mainæœç´¢ç»“æœä½ç½®
archiveGroupByDate = "2006" # "2006-01": group by month, "2006": group by year//ä¸èƒ½æ”¹2006å¹´ä»½
archivePaginate = 13 # æ—¥å¿—æ¯é¡µé¡¹ç›®
paginateWindow = 1
talksPaginate = 5 # å¯¹è¯é¡µé¢ä¸Šæ¯é¡µçš„å…ƒç´ æ•°é‡ã€‚
talksGroupByDate = "2006" # ä¸èƒ½æ”¹2006å¹´ä»½
pubPaginate = 20 # å‘å¸ƒé¡µé¢ä¸Šæ¯é¡µçš„å…ƒç´ æ•°ã€‚
writtenTimeIcon = "ğŸ“…"
modifiedTimeIcon = "ğŸ“"
readingTimeIcon = "â˜•"
authorIcon = "âœï¸"
pagePvIcon = "ğŸ‘€"
pinIcon = "ğŸ“Œ"
tagIcon = "ğŸ·ï¸"
publicationIcon = "ğŸ“š"
typeIcon = "ğŸ¯"

# whoami
myname = "è¯¸è‘›é’çš„ç¼–ç¨‹ä¹‹æ—…" # ç½‘ç«™å
# email = "2110833194.qq" 
whoami = "ğŸ“šè¯¸è‘›ğŸ¤“é’ğŸŒ" # æˆ‘æ˜¯è°ï¼Ÿ
bioImageUrl = "" #å›¾ç‰‡ï¼Œå¤´åƒé“¾æ¥ 
useGravatar = false # æˆ‘ä»¬ä½¿ç”¨æ­¤é€‰é¡¹çš„æœ€é«˜ä¼˜å…ˆçº§
location = "åœ°çƒï¼Œä¸­å›½" # â€œä½ç½®â€
organization = "æ˜Ÿé™…è‡ªç”±è€…" # ç»„ç»‡
link = "https://www.zhugeqing.top" # ç½‘ç«™

# sidebar
enableBio = true # åœ¨ä¸»é¡µä¾§è¾¹æ ä¸­
enableBioImage = true # åœ¨ä¸»é¡µä¾§è¾¹æ ä¸­
enableSidebar = true # è®¾ç½®ä¸ºfalseå¯åˆ›å»ºå†…å®¹çš„å®Œæ•´å®½åº¦ã€‚
enableSidebarTags = true # æ˜¯å¦å¼€å¯tagå›¾æ ‡
#enableSidebarTags = false ï¼ƒ å¦‚æœè¦ä½¿ç”¨æ ‡ç­¾ã€‚
enableSidebarSeries = true # æ˜¯å¦ä½¿ç”¨serier(ç³»åˆ—)
enableSidebarCategories = true # æ˜¯å¦ä½¿ç”¨Categties  (åˆ†ç±»ç›®å½•)
enableHomeSidebarTitles = true # æ˜¯å¦å¼€å¯ä¾§è¾¹æ ‡é¢˜
enableListSidebarTitles = true # æ˜¯å¦å¼€å¯ä¾§è¾¹åˆ—è¡¨æ ‡é¢˜
enableToc = true  # å•é¡µç›®å½•ï¼Œå¯ä»¥å°†æ­¤å‚æ•°æ›¿æ¢ä¸ºtocï¼ˆtoc = trueï¼‰ # æ˜¯å¦å¼€å¯å•é¡µå¿«é€Ÿç´¢å¼•(toc)
hideToc = false 
tocFolding = true
# tocPosition = "inner" # inner, outer tocçš„ä½ç½®
tocPosition = "outer" # inner, outer
enableTocSwitch = true # æ˜¯å¦å¼€å¯tocå¼€å…³
itemsPerCategory = 5 # ä¾§è¾¹æ ä¸­æ˜¾ç¤ºçš„å¸–å­æ•°ä¸Šé™ã€‚
sidebarPosition = "right" # bioï¼Œwhoçš„å¸ƒå±€ä½ç½®
# tocLevels = ["h2", "h3", "h4"]
tocLevels = ["h2","h1", "h3", "h4","h5"]    # æ–‡ç« ä¸­çš„æœ€å°h1ï¼Œæœ€å¤§h5
enableSidebarPostsByOrder = false  # è¾¹æ ä¸­çš„å¦ä¸€ä¸ªåˆ—è¡¨

# footer
showPoweredBy = false # æ˜¾ç¤ºé¡µè„šæ–‡å­—ï¼šç”±Hugoå’ŒZzoä¸»é¢˜æä¾›æ”¯æŒ
showFeedLinks = false # RSSè®¢é˜…
showSocialLinks = true
enableLangChange = false # åœ¨é¡µè„šå·¦ä¸‹æ–¹æ˜¾ç¤ºåˆ‡æ¢è¯­è¨€æŒ‰é’®ã€‚
enableThemeChange = true 

# service
googleTagManager = "" # GTM-XXXXXX
baiduAnalytics = ""
enableBusuanzi = false  # å¦‚æœè®¾ç½®ä¸ºtrueï¼Œåˆ™é¡µé¢æ€»æµè§ˆé‡å°†æ˜¾ç¤ºåœ¨é¡µè„šä¸­ã€‚
busuanziSiteUV = false  # ä¸é‡å¤è®¿å®¢ï¼ˆè®¿å®¢æ€»æ•°ï¼‰
busuanziSitePV = true  # ç½‘ç«™çš„æ€»é¡µé¢æµè§ˆé‡ 
busuanziPagePV = true # æŸ¥çœ‹æ¬¡æ•°

# rss
 updatePeriod = "weekly'" # Possible values: 'hourly', 'daily', 'weekly', 'monthly', or 'yearly'.
 updateFrequency = ""
 fullContents = true

# comment
enableComment = true
disqus_shortname = ""
commento = false

[telegram]
  enable = false
  siteId = ""
  dataLimit = 5

[gitment]          # Gitment is a comment system based on GitHub issues. see https://github.com/imsun/gitment
  owner = ""              # Your GitHub ID
  repo = ""               # The repo to store comments
  clientId = ""           # Your client ID
  clientSecret = ""       # Your client secret

[utterances]       # https://utteranc.es/
  owner = ""              # Your GitHub ID
  repo = ""               # The repo to store comments

[gitalk]           # Gitalk is a comment system based on GitHub issues. see https://github.com/gitalk/gitalk
  owner = ""              # Your GitHub ID
  repo = ""               # The repo to store comments
  clientId = ""           # Your client ID
  clientSecret = ""       # Your client secret

# Valine.
# You can get your appid and appkey from https://leancloud.cn
# more info please open https://valine.js.org
[valine]
 enable = true
 appId = 'wAxnltOf5CPseHAoYzgYcWPK-gzGzoHsz'
 appKey = 'XBIvWNSAW9x396I493MwtR0W'
 notify = false
 verify = false # Verification code
 avatar = 'mm'
 placeholder = 'è¯´ç‚¹ä»€ä¹ˆå§...'
 visitor = false

[changyan]
  changyanAppid = ""        # Changyan app id             # ç•…è¨€
  changyanAppkey = ""       # Changyan app key

[livere]
  livereUID = ""            # LiveRe UID                  # æ¥å¿…åŠ›

# Isso: https://posativ.org/isso/
[isso]
  enable = false
  scriptSrc = "" # "https://isso.example.com/js/embed.min.js"
  dataAttrs = "" # "data-isso='https://isso.example.com' data-isso-require-author='true'"

[socialOptions] # å¦‚æœè®¾ç½®ï¼Œåˆ™ä¼šæ˜¾ç¤ºç¤¾äº¤å›¾æ ‡ã€‚
  # mail = "2110833194@qq.com"
  # phone = ""
  # facebook = "http://example.org/"
  # twitter = "http://example.org/"
  # github = "https://github.com/zzossig/hugo-theme-zzo"
  stack-overflow = ""
  instagram = ""
  google-plus = ""
  youtube = ""
  medium = ""
  tumblr = ""
  linkedin = ""
  pinterest = ""
  stack-exchange = ""
  telegram = ""
  steam = ""
  weibo = ""
  douban = ""
  csdn = ""
  gitlab = ""
  mastodon = ""
  jianshu = ""
  zhihu = ""
  signal = ""
  whatsapp = ""
  matrix = ""
  xmpp = ""
  dev-to = ""
  gitea = ""
  google-scholar = ""

[donationOptions] # å¼€å¯æ‰«ç æ”¯æŒåŠŸèƒ½
  enable = false
  alipay = ""
  wechat = ""
  paypal = ""
  patreon = ""

# possible share name: ["facebook","twitter", "reddit", "linkedin", "tumblr", "weibo", "douban", "line", "pocket", "feedly", "hatena", "pinterest", "delicious", "google"]


[[footerLinks]]
  name = ""
  link = ""
[[footerLinks]]
  name = ""
  link = ""